---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-3
spec:
  minReadySeconds: 1
  selector:
    matchLabels:
      dev: app
  replicas: 2
  template:
    metadata:
      labels:
        dev: app
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - name: app-nginx
              containerPort: 80
        - name: jenkins
          image: jenkins/jenkins
          ports:
            - name: jenkins
              containerPort: 8080


---
apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  selector:
    dev: app
  type: NodePort
  ports:
    - port: 80,8080
      targetPort: 80
      