---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-2
spec:
  minReadySeconds: 1
  selector:
    matchLabels:
      dev: app
  replicas: 1
  template:
    metadata:
      labels:
        dev: app
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - name: nginx
              containerPort: 80


---
apiVersion: v1
kind: Service
metadta:
spec:
  selector:
    dev: app
  type: NodePort
  ports:
    - port: 80
      targetPort: nginx
      nodePort: 31000