---
apiVersion: batch/v1
kind: Job
metadata:
  name: hellojob
spec:
  template:
    metadata:
      name: jobpod
    spec: 
      containers:
         - image: alpine
           potrts:
             - containerport: 2342
           command:
            - sleep
            - 10s

                 