---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: jenkins
spec:
  minReadySeconds: 1
  selector:
      - key: dev
        operator: In
        values:
          - app
          - pre-prod

      - key: prod
        operator: NotIn
        values:
          - qa
          - env
  replicas: 2
  template:
    metadata:
      labels:
        prod: app-version
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins
          ports:
            - name: local
              containerPort: 8080


---
apiVersion: v1
kind: Service
metadata:
  name: service-1
spec:
  selector:
    dev: app
    prod: app-version
  type: NodePort
  ports:
    - port: 8080
      targetPort: local
     