---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: jenkins
spec:
  minReadySeconds: 1
  selector:
    matchExpressions:
      - key: dev
        operator: In
        values:
          - app
          - pre-prod

      - key: prod
        operator: NotIn
        values:
          - qa
          - env
  replicas: 1
  template:
    metadata:
      labels:
        dev: app
        prod: webapp
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins
          ports:
            - name: local
              containerPort: 8080


---
apiVersion: v1
kind: Service
metadata:
  name: service-1
spec:
  selector:
    dev: app
    prod: appversion
  type: NodePort
  ports:
    - port: 8080
      targetPort: local
      nodePort: 31200