---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
spec:
  minReadySceonds: 1
  selector:
    matchExpressions:
      - key: dev
        operator: In
        values:
          - app
          - pre-prod

      - key: prod
        operator: NotIn
        values:
          - qa
          - env
  replicas: 1
  template:
    metadata:
      labels:
        dev: app
        prod: webapp
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80


---
apiVersion: v1
kind: Service
metadta:
spec:
  selector:
    dev: app
    prod: appversion
  type: NodePort
  ports:
    - port: 80
      targetPort: nginx
      nodePort: 31000